function test() {
  throw Error("Failing")
  return "All tests passed";
}
